### ISSUE TITLE
Hello, some bugs, really can't handle. Please consult me.

### ISSUE THREAD

**Issue by GitHubHengheng** [Air14/airhv#12]
I used airhv as Lib, and when I loaded hyperhide, I also ran airhv.

In the virtual machine win10-1703 test, running for a long time, there will be two problems:

Here's a scenario:

win32kfull! AllocateHidData+0xbd

nt! KiSystemServiceCopyEnd+0x13 (TrapFrame @ ffffae01`ec27bb00)

win32u! NtUserFindWindowEx+0x14

USER32! FindWindowW+0xb3

In this case, the location of AllocateHidData+db in windbg is int 3

win32kfull! AllocateHidData+0xb0:

fffff963`7e40252e ebe3            jmp     win32kfull! AllocateHidData+0x9f (fffff963`7e402513)

fffff963`7e402530 cc              int     3

fffff963`7e402531 cc              int     3

fffff963`7e402532 cc              int     3

My understanding is that you enter the kernel by calling NtUserFindWindowEx, and you jump through ept_hook to the address of int 3,

Another problem is:

nt! DbgBreakPointWithStatus

nt! KiBugCheckDebugBreak+0x12

nt! KeBugCheck2+0x922

nt! KeBugCheckEx+0x107

nt! KiBugCheckDispatch+0x69

nt! KiSystemServiceHandler+0x7c

nt! RtlpExecuteHandlerForException+0xd

nt! RtlDispatchException+0x404

nt! KiDispatchException+0x1f6

nt! KiExceptionDispatch+0xce

nt! KiPageFault+0x217 (TrapFrame @ ffffae01`f196d1e0)

win32kfull! GetWindowBordersWithDpiAwareness

win32kfull! xxxInitSendValidateMinMaxInfoEx+0xb2

win32kfull! xxxAdjustSize+0x64

win32kfull! xxxCreateWindowEx+0xf4e

win32kfull! NtUserCreateWindowEx+0x557

nt! KiSystemServiceCopyEnd+0x13 (TrapFrame @ ffffae01`f196db00)

win32u! NtUserCreateWindowEx+0x14

USER32! CreateWindowExW+0x9aa

Page exception blue screen appears,
May I ask if these will appear when you test? In win7, hang up when quite normal.

**Comment by GitHubHengheng** [comment]
The problem is found, but there is no solution for the time being.

In the case of int 3, when the CodeCaves address is executed, the address property becomes executable (at the beginning of the hook page, the property is not executable), and then the ept is not produced, and int 3 is executed.

**Comment by Air14** [comment]
Most likely, this is the same problem as in [HyperDbg](https://github.com/HyperDbg/HyperDbg/issues/91). I'll try changing the code so that each core has its own ept structure, and then see if that fixes the problem, but I'm betting it does.

**Comment by Air14** [comment]
Fixed in commit 31253da586b8b0f9de3f65d4c34e642f38d4dd5e

**Comment by GitHubHengheng** [comment]
> Fixed in commit [31253da](https://github.com/Air14/airhv/commit/31253da586b8b0f9de3f65d4c34e642f38d4dd5e)

Thank you.

**Comment by GitHubHengheng** [comment]
Thank you, thank you very much to share.
