### ISSUE TITLE
current_hooked_page==0 #PF

### ISSUE THREAD

**Issue by progromyang** [Air14/airhv#14]
![QRWSPQ{J%_3)F$FL IP 8G5](https://github.com/Air14/airhv/assets/54520034/a0a3edf4-cc01-477e-a039-bca0e9691ad8)
![}60AYBX{4ISB(0~D3 SI`UG](https://github.com/Air14/airhv/assets/54520034/9988007c-61e7-4ead-984c-290e9ad03164)
这段代码：
current_hooked_page = current_hooked_page->Flink;

current_hooked_page->Flink;    是一个有效结构体数据
current_hooked_page 被赋值以后 值为0 或者一个无效值。这很奇怪。 是否和windbg的dump时机延迟有关系？

**Comment by progromyang** [comment]
是的，在物理机上发生的，
i5-9400F  Win10，
i7-13700  Win11,
这两个机型都出现过指针飞了的情况。
这很奇怪，Entry_List的值是有效的， 但是current_hooked_page  是无效值

**Comment by Air14** [comment]
It also happened to me, a very strange bug and at this point I have no idea what the cause is

**Comment by progromyang** [comment]
我的朋友是这样解释的：
#PF发生时，Entry_List , 也就是 hooked_page_list 他被改为了0，所以.current_hooked_page  是0.
但是window dump的时候，有一个时间差，hooked_page_list又被改为了有效值。
所以在windbg里看，像是 hooked_page_list 是一个完好的链表。
但是我对这种解释抱有怀疑态度！

**Comment by Air14** [comment]
Could you send me your ntbtlog for both systems?

**Comment by progromyang** [comment]
[ntbtlog.txt](https://github.com/Air14/airhv/files/12617350/ntbtlog.txt)
hi，我的朋友。
这个是win10 i5-9400f的 ntbtlog。
这个能看出来什么。。
您还需要win11的吗？

**Comment by Air14** [comment]
Fixed in https://github.com/Air14/airhv/commit/95e2afc0823c6d2b05985cba92a10df65e79c020
