### ISSUE TITLE
Leaked Memory and Invpcid handler

### ISSUE THREAD

**Issue by LegitWalnut** [Air14/airhv#2]
Hi, just wanted to say that this is a very well put together project to learn about virtualization. There are only two problems that I have noticed so far.

First, if it fails at any point in [these lines](https://github.com/Air14/airhv/blob/main/airhv/vmm.cpp#L230-L263) then it will return a nullptr and that memory will not be freed because when you [check if the vcpu is valid ](https://github.com/Air14/airhv/blob/main/airhv/vmm.cpp#L62)it will return false. All you have to do is free all memory allocated up to this point and then return.

Second, I'm not sure if this is intentional because it wasn't working, but your [invpcid ](https://github.com/Air14/airhv/blob/main/airhv/vmexit_handler.cpp#L430-L481)handler has not been added to the [vmexit handler array](https://github.com/Air14/airhv/blob/main/airhv/vmexit_handler.cpp#L100). If this was intentionally left out I would suggest adding a comment explicitly explaining this.

Thanks for reading, and good job on the project.

**Comment by Air14** [comment]
Fixed in [commit](https://github.com/Air14/airhv/commit/9fc73f77dbc405e2bfa521dd5516697af9a92876)
