### ISSUE TITLE
trap flag

### ISSUE THREAD

**Issue by nblog** [Air14/airhv#3]
like: https://github.com/tandasat/HyperPlatform/issues/26

cause this phenomenon to https://github.com/Air14/HyperHide/issues/16

i don't think it has anything to do with rdtsc instruct.

maybe you should check the trap flag.
[vmexit_cpuid_handler](https://github.com/Air14/airhv/blob/main/airhv/vmexit_handler.cpp#L467)
[vmexit_rdtsc_handler](https://github.com/Air14/airhv/blob/main/airhv/vmexit_handler.cpp#L1154)

**Comment by Air14** [comment]
fixed in latest commit
