### ISSUE TITLE
can i hook a proc in R3

### ISSUE THREAD

**Issue by kkptm** [Air14/airhv#6]
if winver<= win10(1809):
good.
winver >1909:
throw error at ept.cpp->hook_function->{hooked_page_info->entry_address->execute =0;}.

**Comment by kkptm** [comment]
how can i fix it?
can you help me?

**Comment by Air14** [comment]
Does it throw an error when hooking r3 function or r0?

**Comment by kkptm** [comment]
yes , in R3

**Comment by kkptm** [comment]
Only in winver>1809

**Comment by Air14** [comment]
Well, this project is not designed to hook user mode functions, I suggest you use this hyperisor https://github.com/wbenny/hvpp which has an example of how to hook um functions

**Comment by kkptm** [comment]
ok thanks
